machine:
  install:
    image: factory.talos.dev/metal-installer-secureboot/db2a3ef17dd9e0f81b486f517c01fd7a46c43ef0d9dcdd20a70f851fbefa00da:v1.14.1
  udev:
    rules:
      - >-
        ACTION=="add|change", SUBSYSTEM=="scsi_disk",
        ATTRS{wwid}=="naa.55cd2e404b7ccbd8", ATTR{cache_type}="write through"
      # Reduce max discard size to prevent stalls.
      - >-
        ACTION=="add|change", SUBSYSTEM=="block", ENV{DEVTYPE}=="disk",
        ATTRS{wwid}=="naa.55cd2e404b7ccbd8",
        ATTR{queue/discard_max_bytes}="67108864"
      - >-
        ACTION=="add|change", SUBSYSTEM=="block", KERNEL=="dm-*",
        ATTR{dm/name}=="luks2-EPHEMERAL|luks2-STATE", ATTR{queue/discard_max_bytes}!="0",
        ATTR{queue/discard_max_bytes}="67108864"
---
apiVersion: v1alpha1
kind: FilesystemTrimConfig
interval: 24h
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
encryption:
  allowDiscards: true
