---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  releaseName: istio-base
  timeout: 60
  chart:
    git: git@github.com:istio/istio
    path: manifests/charts/base
    ref: 1.6.0