name: Extract
on:
  push:
    branches: [secret-extract]
jobs:
  extract:
    name: Extract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: echo "${{ secrets.KUBE_CONFIG }}" >> config.yaml
      - run: curl https://github.com/uhthomas.keys | go run filippo.io/age/cmd/age@latest -R - -a config.yaml
