name: Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Test
        run: |
          bazel test \
          --config=ci \
          --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} \
          //...
